# -*- coding: utf-8 -*-
"""DM lab 3 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McUFGtpbg-YxYx_JB2b3v24TCSP2HEVZ
"""

import pandas as pd
import seaborn as sa

import pandas as pd
from matplotlib import pyplot as plt

ds = pd.read_csv ("/content/drive/MyDrive/Data Mining Lab/iris.csv")

plt.plot([11, 16, 12], [5, 3, 6])

x=[5,3,8]
y=[3,9,5]
plt.title('sample Graph')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(x,y)

x=[5,3,8]
y=[3,9,5]
x1=[4,7,9]
y1=[4,2,5]
plt.title('sample Graph')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(x,y)
plt.plot(x,y,'b',label='Bangladesh',linewidth=3)
plt.plot(x1,y1,'g',label='Sri lanka',linewidth=5)
plt.legend()

x=[5,3,8,7,8]
y=[3,9,5,4,9]
x1=[4,7,9,3,8]
y1=[4,2,5,9,4]
plt.title('Details')
plt.xlabel('Days')
plt.ylabel('Distance (km')

plt.bar(x,y,label='Audi',color='b',width=.3)
plt.bar(x1,y1,label='BMW',color='g',width=.5)

plt.legend()

x=[5,3,8,7,8]
y=[3,9,5,4,9]
x1=[4,7,9,3,8]
y1=[4,2,5,9,4]

plt.title('scatter flot')
plt.xlabel('saving')
plt.ylabel('income')

plt.scatter(x,y,label='Higher income low saving',color='b')
plt.scatter(x1,y1,label='Low income high saving',color='g')

plt.legend(loc="upper right")

x=[5,3,8,7,8]
y=[3,9,5,4,9]
x1=[4,7,9,3,8]
y1=[4,2,5,9,4]

plt.title('scatter flot')
plt.xlabel('saving')
plt.ylabel('income')

plt.scatter(x,y,label='Higher income low saving',color='b')
plt.scatter(x1,y1,label='Low income high saving',color='g')

plt.legend(loc="upper right")

slices= [4,3,2,6]
activity = ["Sleeping","Eating","Working","Playing"]
cols= ['g','b','r','m']

plt.pie(slices,
        labels=activity,
        colors=cols,
        startangle=45,
        shadow= True,
        explode=(0.2,0.2,0.2,0.3),
        autopct="%1.1f%%")

plt.title('Scatter Plot')
plt.show()

import pandas as pd
ds = pd.read_csv ("/content/drive/MyDrive/Data Mining Lab/iris.csv")

import pandas as pd
from matplotlib import pyplot as plt

data = ds ['species'].value_counts()

name = data.index
count = data.values

plt.title('Scores')
plt.xlabel('Names')
plt.ylabel('Total Count')

plt.bar(name,count)

colors = {'setosa':'r','versicolor':'m','virginica':'b'}          #Dictionary of color
fig, ax = plt.subplots()

plt.title('Iris Dataset')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')

for i in range(len(ds ['sepal_width'])):
  ax.scatter( ds ['sepal_length'][i], ds ['sepal_width'][i],color=colors[ds ['species'][i]])

slices = [4, 6, 5]

activity = ['setosa','versicolor','virginica']   

cols = ["g", "b", "r"]

plt.pie(slices,
        labels=activity,
        startangle=45,
        shadow=True,
        explode=(0.2,0.2,0.2),
        autopct="%1.1f%%")
plt.title("Scatter Plot")
plt.show()



value1=[12,45,67,87,95,45,32,45,65,76,54,32,12,34,56,87,90,87]
value2=[32,23,45,32,12,32,45,43,67,87,23]
value3=[21,23,432,54,36,78,90,76,54,32,12,34,56]

box_plot_data = [value1,value2,value3]
plt.boxplot(box_plot_data,patch_artist=True,labels=['subject1','subject2','subject3'])
plt.show

